projects:
  blogapp:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\apiqueries\query.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src\app\graphAPI.service.ts
        docsFilePath: src\graphql
        graphQLApiId: ezayf5owfjgizlm5chsk3lmppy
      endpoints:
        prod: >-
          https://up772srfhvdxreukxpjoucmuhi.appsync-api.us-west-2.amazonaws.com/graphql
